// GENERATED FILE — do not edit by hand.
// Source of truth: project-text-content.md (EN) × upload/project-text-content-ar.md (AR)
// Rebuild with: bun scripts/build-ar-dict.mjs
// Exact-match EN→AR dictionary for the Arabic UI text layer (ar-text.ts).
// Dynamic templates are handled by pattern rules in ar-text.ts, not here.

export const AR_DICT: Record<string, string> = {
  "Trending Movies": "الأفلام الرائجة",
  "In Theaters": "في دور العرض",
  "Trending Series": "المسلسلات الرائجة",
  "Popular Series": "المسلسلات الشائعة",
  "Top Rated Series": "المسلسلات الأعلى تقييمًا",
  "Top 10 today": "أفضل 10 اليوم",
  "Top 10 Today": "أفضل 10 اليوم",
  "trending on Stremio": "الرائج على Stremio",
  "Unable to load catalog. Check your connection.": "تعذر تحميل الكتالوج. تحقق من اتصالك.",
  "Cinemeta provides the default catalog; install addons for more.": "يوفر Cinemeta الكتالوج الافتراضي؛ ثبّت إضافات للحصول على المزيد.",
  "Featured": "مميز",
  "active slide title / empty string for inactive": "عنوان الشريحة النشطة / سلسلة فارغة للشريحة غير النشطة",
  "View details": "عرض التفاصيل",
  "Pause autoplay / استئناف… → exact: Pause autoplay *(when playing)*; Resume autoplay": "إيقاف العرض التلقائي / استئناف… → exact: إيقاف العرض التلقائي *(when playing)*; استئناف العرض التلقائي",
  "Loading featured titles": "جارٍ تحميل المميزة",
  "Continue Watching": "متابعة المشاهدة",
  "New episode": "حلقة جديدة",
  "Mark as watched": "تحديد كمشاهد",
  "Remove from Continue Watching": "إزالة من متابعة المشاهدة",
  "Marked as watched": "تم التحديد كمشاهد",
  "Play": "تشغيل",
  "Details": "التفاصيل",
  "Unable to load catalog content.": "تعذر تحميل محتوى الكتالوج.",
  "Top Rated Movies": "الأفلام الأعلى تقييمًا",
  "Family Picks": "اختيارات العائلة",
  "Adventures": "المغامرات",
  "Mystery Series": "مسلسلات الغموض",
  "Romance": "الرومانسية",
  "History & War": "التاريخ والحرب",
  "Music & Musicals": "الموسيقى والاستعراضات",
  "Popular Movies": "الأفلام الشائعة",
  "Top Rated": "الأعلى تقييمًا",
  "Action": "أكشن",
  "Comedy": "كوميديا",
  "Sci-Fi & Fantasy": "خيال علمي وفانتازيا",
  "Horror": "رعب",
  "Drama": "دراما",
  "Animation": "رسوم متحركة",
  "Documentary": "وثائقي",
  "Drama Series": "مسلسلات دراما",
  "Comedy Series": "مسلسلات كوميديا",
  "Crime & Mystery": "الجريمة والغموض",
  "Reality": "برامج الواقع",
  "Anime": "أنمي",
  "Catalog by AniList · click any title to resolve into your Stremio catalogs": "كتالوج عبر AniList · انقر على أي عنوان لتحويله إلى كتالوجات Stremio الخاصة بك",
  "Retry": "إعادة المحاولة",
  "Trending Now": "الرائج الآن",
  "Popular This Season": "الشائع هذا الموسم",
  "All-Time Best": "الأفضل على الإطلاق",
  "Anime Movies": "أفلام الأنمي",
  "Upcoming Next Season": "القادم في الموسم التالي",
  "Stremio catalogs": "كتالوجات Stremio",
  "Anime catalogs from Cinemeta and your installed addons": "كتالوجات الأنمي من Cinemeta وإضافاتك المثبتة",
  "From Stremio Catalogs": "من كتالوجات Stremio",
  "Trending anime spotlight": "أبرز الأنمي الرائج",
  "Find streams": "البحث عن التدفقات",
  "AniList page": "صفحة AniList",
  "Resolving…": "جارٍ التحويل…",
  "Not in Cinemeta — showing search results": "غير موجود في Cinemeta — يتم عرض نتائج البحث",
  "Kids Corner": "زاوية الأطفال",
  "Fun and safe picks for the little ones.": "اختيارات ممتعة وآمنة للصغار.",
  "Poster size in Kids Corner — bigger cards are easier to tap.": "حجم الملصقات في زاوية الأطفال — البطاقات الأكبر أسهل للمس.",
  "Card size": "حجم البطاقة",
  "Large": "كبير",
  "Medium": "متوسط",
  "Small": "صغير",
  "Animated Movies": "أفلام الرسوم المتحركة",
  "Family Movies": "أفلام عائلية",
  "Kids TV": "تلفزيون الأطفال",
  "Family Shows": "مسلسلات عائلية",
  "Sing-Along": "غنِّ معنا",
  "No kids content available right now.": "لا يتوفر محتوى للأطفال حاليًا.",
  "Add playlist": "إضافة قائمة تشغيل",
  "Add IPTV playlist": "إضافة قائمة تشغيل IPTV",
  "Name": "الاسم",
  "My playlist": "قائمة التشغيل الخاصة بي",
  "M3U / EPG URL": "عنوان URL لـ M3U / EPG",
  "Add": "إضافة",
  "Remove {pl.name}": "إزالة {pl.name}",
  "Filter channels…": "تصفية القنوات…",
  "Filter channels": "تصفية القنوات",
  "All ({channels.length})": "الكل ({channels.length})",
  "General": "عام",
  "Failed to load playlists.": "فشل تحميل قوائم التشغيل.",
  "Unknown": "غير معروف",
  "Program": "برنامج",
  "No playlists yet. Add an M3U playlist to watch live TV.": "لا توجد قوائم تشغيل بعد. أضف قائمة تشغيل M3U لمشاهدة التلفزيون المباشر.",
  "Horse is a neutral client — bring your own playlists.": "Horse هو عميل محايد — أضف قوائم التشغيل الخاصة بك.",
  "Now: {prog.title}": "الآن: {prog.title}",
  "Live": "مباشر",
  "No channels match your filters.": "لا توجد قنوات تطابق عوامل التصفية.",
  "Weekly airing schedule for series you track — from your watchlist, continue watching and history.": "جدول البث الأسبوعي للمسلسلات التي تتابعها — من قائمة المشاهدة، والمتابعة، والسجل.",
  "Previous week": "الأسبوع السابق",
  "Prev": "السابق",
  "Today": "اليوم",
  "Next week": "الأسبوع التالي",
  "Next": "التالي",
  "Loading episodes…": "جارٍ تحميل الحلقات…",
  "Day of week": "يوم الأسبوع",
  "Mon / Tue / Wed / Thu / Fri / Sat / Sun": "الإثنين / الثلاثاء / الأربعاء / الخميس / الجمعة / السبت / الأحد",
  "No episodes": "لا توجد حلقات",
  "Watched": "تمت المشاهدة",
  "Soon": "قريبًا",
  "Anime airing this week": "الأنمي الذي سيُعرض هذا الأسبوع",
  "No airing data for this week.": "لا توجد بيانات بث لهذا الأسبوع.",
  "Series with new episodes this week": "المسلسلات ذات الحلقات الجديدة هذا الأسبوع",
  "New episodes this week": "حلقات جديدة هذا الأسبوع",
  "No tracked series yet": "لا توجد مسلسلات متابَعة بعد",
  "Add shows to your watchlist or start watching, and their weekly episode air dates will appear here automatically.": "أضف مسلسلات إلى قائمة المشاهدة أو ابدأ المشاهدة، وستظهر مواعيد بث حلقاتها الأسبوعية هنا تلقائيًا.",
  "Browse shows": "تصفح المسلسلات",
  "Watchlist · Lists · History": "قائمة المشاهدة · القوائم · السجل",
  "Your watchlist is empty. Add titles from any detail page.": "قائمة المشاهدة فارغة. أضف العناوين من أي صفحة تفاصيل.",
  "Open": "فتح",
  "New list": "قائمة جديدة",
  "No lists yet. Curate themed collections like “Comfort watches”.": "لا توجد قوائم بعد. أنشئ مجموعات ذات طابع خاص مثل «مشاهدات مريحة».",
  "Open list {list.name}": "فتح القائمة {list.name}",
  "No description": "لا يوجد وصف",
  "Rename list {list.name}": "إعادة تسمية القائمة {list.name}",
  "Delete?": "حذف؟",
  "Confirm delete": "تأكيد الحذف",
  "Cancel delete": "إلغاء الحذف",
  "Delete list {list.name}": "حذف القائمة {list.name}",
  "No watch history yet.": "لا يوجد سجل مشاهدة بعد.",
  "Create list": "إنشاء قائمة",
  "Create a new list": "إنشاء قائمة جديدة",
  "e.g. Space epics": "مثال: ملاحم الفضاء",
  "Description (optional)": "الوصف (اختياري)",
  "What belongs here?": "ماذا يوجد هنا؟",
  "Cancel": "إلغاء",
  "Edit list": "تعديل القائمة",
  "List name": "اسم القائمة",
  "List description": "وصف القائمة",
  "Save": "حفظ",
  "Created “{list.name}”": "تم إنشاء «{list.name}»",
  "List deleted": "تم حذف القائمة",
  "This list no longer exists.": "هذه القائمة لم تعد موجودة.",
  "Loading list…": "جارٍ تحميل القائمة…",
  "Edit": "تعديل",
  "Share": "مشاركة",
  "Share list {list.name}": "مشاركة القائمة {list.name}",
  "Delete list?": "حذف القائمة؟",
  "Yes": "نعم",
  "This list is empty. Open any title and choose “Add to list”.": "هذه القائمة فارغة. افتح أي عنوان واختر «إضافة إلى القائمة».",
  "Browse titles": "تصفح العناوين",
  "Remove {item.name} from {list.name}": "إزالة {item.name} من {list.name}",
  "Share list link": "رابط مشاركة القائمة",
  "Share “{list.name}”": "مشاركة «{list.name}»",
  "Copy this link to share your list. It contains only titles and poster URLs — nothing is sent to any server.": "انسخ هذا الرابط لمشاركة قائمتك. يحتوي فقط على العناوين وروابط الملصقات — ولا يتم إرسال أي شيء إلى أي خادم.",
  "Share link": "رابط المشاركة",
  "Close": "إغلاق",
  "Copy again": "نسخ مرة أخرى",
  "e.g. Weekend sci-fi": "مثال: خيال علمي لعطلة نهاية الأسبوع",
  "What is this list about?": "ما موضوع هذه القائمة؟",
  "List updated": "تم تحديث القائمة",
  "Could not build share link": "تعذر إنشاء رابط المشاركة",
  "Share link copied · (toast description) Anyone opening it can import this list.": "تم نسخ رابط المشاركة · (toast description) يمكن لأي شخص يفتحه استيراد هذه القائمة.",
  "Copy blocked — copy the link manually": "تعذر النسخ — انسخ الرابط يدويًا",
  "Share link copied": "تم نسخ رابط المشاركة",
  "Still blocked — select the text and copy manually": "لا يزال النسخ محظورًا — حدّد النص وانسخه يدويًا",
  "Go back": "رجوع",
  "Filter by genre": "تصفية حسب النوع",
  "All": "الكل",
  "Fallback genre chips when no addon declares them — Movies: Action, Adventure, Animation, Comedy, Crime, Documentary, Drama, Family, Fantasy, History, Horror, Music, Mystery, Romance, Sci-Fi & Fantasy, Science Fiction, Thriller, War, Western": "شرائح الأنواع الاحتياطية عند عدم إعلان أي إضافة عنها — الأفلام: أكشن، مغامرات، رسوم متحركة، كوميديا، جريمة، وثائقي، دراما، عائلة، فانتازيا، تاريخ، رعب، موسيقى، غموض، رومانسي، خيال علمي وفانتازيا، خيال علمي، إثارة، حرب، ويسترن",
  "Fallback genre chips — Series: Action, Adventure, Animation, Comedy, Crime, Documentary, Drama, Family, Fantasy, History, Horror, Mystery, Romance, Sci-Fi & Fantasy, Science Fiction, Thriller, War, Western, Kids, Reality, War & Politics": "شرائح الأنواع الاحتياطية — المسلسلات: أكشن، مغامرات، رسوم متحركة، كوميديا، جريمة، وثائقي، دراما، عائلة، فانتازيا، تاريخ، رعب، غموض، رومانسي، خيال علمي وفانتازيا، خيال علمي، إثارة، حرب، ويسترن، أطفال، واقع، حرب وسياسة",
  "Search catalog…": "البحث في الكتالوج…",
  "Clear search": "مسح البحث",
  "Clear all": "مسح الكل",
  "Clear all filters": "مسح جميع عوامل التصفية",
  "Failed to load catalog": "فشل تحميل الكتالوج",
  "No items match the active filters.": "لا توجد عناصر تطابق عوامل التصفية النشطة.",
  "This catalog returned no items.": "لم يُرجع هذا الكتالوج أي عناصر.",
  "Clear filters": "مسح عوامل التصفية",
  "Loading details…": "جارٍ تحميل التفاصيل…",
  "Title not found. It may not be in Cinemeta or your addons.": "العنوان غير موجود. قد لا يكون موجودًا في Cinemeta أو إضافاتك.",
  "Failed to load details": "فشل تحميل التفاصيل",
  "Title not found.": "العنوان غير موجود.",
  "Content rating": "تصنيف المحتوى",
  "Streams": "التدفقات",
  "Choose a specific stream": "اختر تدفقًا محددًا",
  "(aria-pressed toggle) In watchlist / Watchlist": "(aria-pressed toggle) في قائمة المشاهدة / قائمة المشاهدة",
  "In watchlist": "في قائمة المشاهدة",
  "Watchlist": "قائمة المشاهدة",
  "Director": "المخرج",
  "Starring": "بطولة",
  "Press Play to fetch streams from your installed addons for this title.": "اضغط على تشغيل لجلب التدفقات لهذا العنوان من الإضافات المثبتة لديك.",
  "No episode information available for this series.": "لا تتوفر معلومات عن حلقات هذا المسلسل.",
  "Episodes": "الحلقات",
  "Newest first": "الأحدث أولًا",
  "Oldest first": "الأقدم أولًا",
  "Select season": "اختيار الموسم",
  "Recommended by TMDB": "موصى به من TMDB",
  "Recommended for you": "موصى به لك",
  "via TMDB": "عبر TMDB",
  "More like this": "المزيد مثل هذا",
  "Horse is a neutral client for the open Stremio addon protocol. Install catalogs, streams and subtitles addons by manifest URL. Horse hosts no content — you bring your own addons.": "Horse هو عميل محايد لبروتوكول إضافات Stremio المفتوح. ثبّت إضافات الكتالوجات والتدفقات والترجمات عبر رابط manifest. لا يستضيف Horse أي محتوى — أنت تضيف إضافاتك بنفسك.",
  "Addon health summary": "ملخص حالة الإضافة",
  "Re-test all": "إعادة اختبار الكل",
  "Re-test every checked addon": "إعادة اختبار كل إضافة تم فحصها",
  "Addon manifest URL": "رابط manifest الخاص بالإضافة",
  "Install": "تثبيت",
  "Installing…": "جارٍ التثبيت…",
  "No addons installed yet.": "لا توجد إضافات مثبتة بعد.",
  "No addons match your filter.": "لا توجد إضافات تطابق عامل التصفية.",
  "Testing addon": "جارٍ اختبار الإضافة",
  "Addon healthy": "الإضافة سليمة",
  "Addon not responding": "الإضافة لا تستجيب",
  "Test addon": "اختبار الإضافة",
  "Disable / Enable": "تعطيل / تمكين",
  "Configure": "تهيئة",
  "Uninstall": "إلغاء التثبيت",
  "HEALTHY": "سليم",
  "NO REPLY": "لا توجد استجابة",
  "· {x.x}s": "· {x.x}ث",
  "Last check {toLocaleString()}": "آخر فحص {toLocaleString()}",
  "Community addons": "إضافات المجتمع",
  "Cinemeta — Official Stremio catalog & metadata for movies and series.": "Cinemeta — كتالوج Stremio الرسمي والبيانات الوصفية للأفلام والمسلسلات.",
  "OpenSubtitles v3 — Subtitles from the OpenSubtitles community addon.": "OpenSubtitles v3 — ترجمات من إضافة مجتمع OpenSubtitles.",
  "Stremio Community Addons catalog — Meta-catalog of community addons.": "كتالوج إضافات مجتمع Stremio — كتالوج شامل لإضافات المجتمع.",
  "Installed": "مثبتة",
  "(toast, dynamic) probe result title/body": "(toast, dynamic) عنوان/نص نتيجة الفحص",
  "Addon not found.": "الإضافة غير موجودة.",
  "empty": "فارغ",
  "Types": "الأنواع",
  "Resources": "الموارد",
  "Catalogs": "الكتالوجات",
  "Contact": "جهة الاتصال",
  "None": "لا شيء",
  "Transport URL:": "عنوان URL للنقل:",
  "Every catalog exposed by your installed addons, in one place.": "كل كتالوج توفره إضافاتك المثبتة، في مكان واحد.",
  "No catalogs yet.": "لا توجد كتالوجات بعد.",
  "Install addons": "تثبيت الإضافات",
  "Searchable": "قابل للبحث",
  "needs search term": "يحتاج إلى مصطلح بحث",
  "Loading your stats…": "جارٍ تحميل إحصاءاتك…",
  "Couldn't generate card": "تعذر إنشاء البطاقة",
  "Share stats": "مشاركة الإحصاءات",
  "Share card downloaded": "تم تنزيل بطاقة المشاركة",
  "Everything you've watched on this device, computed locally.": "كل ما شاهدته على هذا الجهاز، محسوب محليًا.",
  "Total watch time": "إجمالي وقت المشاهدة",
  "Movies": "الأفلام",
  "Active days": "الأيام النشطة",
  "Last 14 days": "آخر 14 يومًا",
  "Watch activity chart": "مخطط نشاط المشاهدة",
  "Last 365 days": "آخر 365 يومًا",
  "365-day watch activity heatmap": "خريطة نشاط المشاهدة لآخر 365 يومًا",
  "Less": "أقل",
  "More": "أكثر",
  "Achievements": "الإنجازات",
  "Most watched": "الأكثر مشاهدة",
  "Top genres": "أفضل الأنواع",
  "Resolving genres": "جارٍ تحديد الأنواع",
  "Genres unavailable — could not reach Cinemeta for these titles.": "الأنواع غير متاحة — تعذر الوصول إلى Cinemeta لهذه العناوين.",
  "No genre data for your watch history yet.": "لا توجد بيانات أنواع لسجل مشاهدتك بعد.",
  "Stats are computed locally from your watch history. Private by design — nothing leaves this device unless you sign in to Stremio.": "تُحسب الإحصاءات محليًا من سجل المشاهدة لديك. الخصوصية مصممة بهذا الشكل — لا يغادر أي شيء هذا الجهاز إلا إذا سجلت الدخول إلى Stremio.",
  "Watch time": "وقت المشاهدة",
  "Top title": "العنوان الأعلى",
  "Your year in stories": "عامك في القصص",
  "Watch time, active days, top titles and genres — computed locally from your watch history on this device. Nothing leaves your browser unless you sign in yourself.": "وقت المشاهدة، والأيام النشطة، وأفضل العناوين والأنواع — تُحسب محليًا من سجل المشاهدة على هذا الجهاز. لا يغادر أي شيء متصفحك إلا إذا سجلت الدخول بنفسك.",
  "Browse Movies": "تصفح الأفلام",
  "Top Shows": "أفضل المسلسلات",
  "Open Live TV": "فتح البث التلفزيوني المباشر",
  "Stream picker": "منتقي التدفقات",
  "Choose a stream": "اختر تدفقًا",
  "Refresh streams · (tooltip) Refresh": "تحديث التدفقات · (tooltip) تحديث",
  "Close picker": "إغلاق المنتقي",
  "Free": "مجاني",
  "Cached": "مخزن مؤقتًا",
  "Showing all": "عرض الكل",
  "Playable here": "قابل للتشغيل هنا",
  "Showing every stream": "عرض جميع التدفقات",
  "Filter…": "تصفية…",
  "Filter streams": "تصفية التدفقات",
  "Torrent streams play through the built-in P2P engine — no account needed. Connect debrid for instant cached links.": "تعمل تدفقات التورنت عبر محرك P2P المدمج — لا حاجة إلى حساب. اربط debrid للحصول على روابط مخزنة مؤقتًا بشكل فوري.",
  "Connect": "اتصال",
  "No stream addons installed. Install a stream addon to watch titles.": "لا توجد إضافات تدفقات مثبتة. ثبّت إضافة تدفقات لمشاهدة العناوين.",
  "Failed to fetch streams": "فشل جلب التدفقات",
  "No streams match. Try refreshing or removing filters.": "لا توجد تدفقات مطابقة. جرّب التحديث أو إزالة عوامل التصفية.",
  "Stream": "تدفق",
  "Compatibility badges (label / tooltip):": "شارات التوافق (التسمية / التلميح):",
  "Preparing file… / Joining swarm…": "جارٍ تجهيز الملف… / جارٍ الانضمام إلى السرب…",
  "Connecting…": "جارٍ الاتصال…",
  "Play via P2P *(when no debrid key)* / Play via P2P torrent engine": "التشغيل عبر P2P *(when no debrid key)* / التشغيل عبر محرك تورنت P2P",
  "Play free via the built-in P2P engine / Play via the built-in P2P engine (slower)": "تشغيل مجاني عبر محرك P2P المدمج / التشغيل عبر محرك P2P المدمج (أبطأ)",
  "Unlock": "فتح القفل",
  "Unlocking…": "جارٍ فتح القفل…",
  "Unlock with debrid": "فتح القفل باستخدام debrid",
  "Connect a debrid service for instant links / Unlock with your debrid service": "اربط خدمة debrid للحصول على روابط فورية / افتح القفل باستخدام خدمة debrid",
  "Unlock failed": "فشل فتح القفل",
  "P2P stream failed": "فشل تدفق P2P",
  "Could not find peers for this torrent. The swarm may be dead or this network blocks BitTorrent — a debrid service would unlock it instantly.": "تعذر العثور على أقران لهذا التورنت. قد يكون السرب متوقفًا أو قد تحظر هذه الشبكة BitTorrent — ستفتح خدمة debrid القفل فورًا.",
  "Connect a debrid service": "ربط خدمة debrid",
  "Connect debrid": "ربط debrid",
  "Instant cached streams — your key stays in this browser.": "تدفقات مخزنة مؤقتًا بشكل فوري — يبقى مفتاحك في هذا المتصفح.",
  "(aria, radiogroup) Debrid service": "(aria, radiogroup) خدمة Debrid",
  "Paste your Real-Debrid API key / Paste your AllDebrid API key": "ألصق مفتاح API الخاص بـ Real-Debrid / ألصق مفتاح API الخاص بـ AllDebrid",
  "That API key looks too short — copy the full key from your account page.": "يبدو مفتاح API قصيرًا جدًا — انسخ المفتاح الكامل من صفحة حسابك.",
  "Could not verify the key.": "تعذر التحقق من المفتاح.",
  "Verifying…": "جارٍ التحقق…",
  "Get key": "الحصول على المفتاح",
  "Open your account page to find the API key": "افتح صفحة حسابك للعثور على مفتاح API",
  "No debrid account? Torrents still play free via the built-in P2P engine — debrid just makes cached streams instant.": "ليس لديك حساب debrid؟ لا تزال التورنتات تعمل مجانًا عبر محرك P2P المدمج — debrid يجعل التدفقات المخزنة مؤقتًا فورية فقط.",
  "Settings": "الإعدادات",
  "Settings sections": "أقسام الإعدادات",
  "Basics": "الأساسيات",
  "Player": "المشغل",
  "Theme": "المظهر",
  "Language": "اللغة",
  "Integrations": "التكاملات",
  "Data": "البيانات",
  "About": "حول",
  "Instant play / Open the best stream immediately when clicking Play": "التشغيل الفوري / افتح أفضل تدفق مباشرةً عند الضغط على تشغيل",
  "Auto-play next episode / Continue to the next episode automatically": "التشغيل التلقائي للحلقة التالية / انتقل إلى الحلقة التالية تلقائيًا",
  "Resume playback / Pick up where you left off": "استئناف التشغيل / تابع من حيث توقفت",
  "Confirm leaving playback / Ask before closing the player": "تأكيد مغادرة التشغيل / اسأل قبل إغلاق المشغل",
  "Show card badges / IMDb rating badges on posters": "إظهار شارات البطاقات / شارات تقييم IMDb على الملصقات",
  "Home mode / Horse layout with hero, or classic rows only": "وضع الصفحة الرئيسية / تخطيط Horse مع الواجهة الرئيسية، أو الصفوف الكلاسيكية فقط",
  "Show all addon rows on home / Include every addon catalog row": "إظهار جميع صفوف الإضافات في الصفحة الرئيسية / تضمين كل صف من كتالوجات الإضافات",
  "Hide watched in catalogs / Filter titles you already watched": "إخفاء المشاهَد في الكتالوجات / تصفية العناوين التي شاهدتها بالفعل",
  "Auto-hide navigation bar / Hide the glass dock scrolling down, reveal scrolling up": "إخفاء شريط التنقل تلقائيًا / إخفاء الرصيف الزجاجي أثناء التمرير لأسفل، وإظهاره أثناء التمرير لأعلى",
  "Use secure proxy when needed / Routes blocked streams through this server (fixes CORS and source headers)": "استخدام وكيل آمن عند الحاجة / توجيه التدفقات المحظورة عبر هذا الخادم (إصلاح CORS ورؤوس المصدر)",
  "(segment options) Auto / Always / Never": "(segment options) تلقائي / دائمًا / أبدًا",
  "Convert incompatible streams / MKV/HEVC/AC3-DTS → H.264/AAC on the server (uses CPU)": "تحويل التدفقات غير المتوافقة / MKV/HEVC/AC3-DTS → H.264/AAC على الخادم (يستخدم CPU)",
  "(segment options) Auto / Ask / Never": "(segment options) تلقائي / سؤال / أبدًا",
  "Show only streams that play in the browser / The stream picker hides unplayable sources by default": "إظهار التدفقات القابلة للتشغيل في المتصفح فقط / يخفي منتقي التدفقات المصادر غير القابلة للتشغيل افتراضيًا",
  "Prefer H.264/AAC / Rank browser-safe codecs above HEVC when sorting streams": "تفضيل H.264/AAC / ترتيب برامج الترميز الآمنة للمتصفح قبل HEVC عند فرز التدفقات",
  "Video fill / How video fits the screen": "ملء الفيديو / كيفية ملاءمة الفيديو للشاشة",
  "Player chrome / Stremio-style or Horse-style controls": "هيكل المشغل / عناصر تحكم بأسلوب Stremio أو Horse",
  "Stream picker layout / Condensed rows or Stremio-style tiers": "تخطيط منتقي التدفقات / صفوف مختصرة أو مستويات بأسلوب Stremio",
  "Quality info in picker / Show codec, size and source details": "معلومات الجودة في المنتقي / عرض برنامج الترميز والحجم وتفاصيل المصدر",
  "Appearance / Light or dark Material 3 scheme of your current palette": "المظهر / مخطط Material 3 فاتح أو داكن من لوحة الألوان الحالية",
  "(segment options) Dark / Light": "(segment options) داكن / فاتح",
  "Contrast / Scheme contrast level — higher for stronger legibility": "التباين / مستوى تباين المخطط — أعلى لتسهيل القراءة",
  "(segment options) Standard / Medium / High": "(segment options) قياسي / متوسط / عالٍ",
  "Theme Studio": "استوديو المظهر",
  "Build a fully custom palette, fonts and layout — with live preview. Your accent color seeds the Material 3 palette.": "أنشئ لوحة ألوان وخطوطًا وتخطيطًا مخصصًا بالكامل — مع معاينة مباشرة. لونك المميز هو الأساس للوحة Material 3.",
  "Open Theme Studio": "فتح استوديو المظهر",
  "Your saved themes": "السمات المحفوظة",
  "Theme presets": "السمات الجاهزة",
  "Your accent color seeds the Material 3 palette.": "لونك المميز هو الأساس للوحة Material 3.",
  "preset display names rendered here but defined in lib/harbor/themes.ts: Horse · Nord · Stremio · Crunchy · Royal · Dracula · Forest · Noir · Aurora · Velvet · MinUI": "أسماء السمات المعروضة هنا والمُعرّفة في lib/harbor/themes.ts: Horse · Nord · Stremio · Crunchy · Royal · Dracula · Forest · Noir · Aurora · Velvet · MinUI",
  "Font pairing": "تنسيق الخطوط",
  "font-pair names rendered here but defined in lib/harbor/themes.ts: Sentient / Switzer · Fraunces / Inter · General Sans · Cabinet / Switzer · IBM Plex · Plus Jakarta · System": "أسماء أزواج الخطوط المعروضة هنا والمُعرّفة في lib/harbor/themes.ts: Sentient / Switzer · Fraunces / Inter · General Sans · Cabinet / Switzer · IBM Plex · Plus Jakarta · System",
  "Custom background": "الخلفية المخصصة",
  "Upload image": "رفع صورة",
  "Remove": "إزالة",
  "Dim": "تعتيم",
  "Upload background image": "رفع صورة الخلفية",
  "Image too large · (toast description) Use an image under 3 MB.": "الصورة كبيرة جدًا · (toast description) استخدم صورة أقل من 3 ميجابايت.",
  "Preferred subtitle languages": "لغات الترجمة المفضلة",
  "Toggle languages below, then order them — the player picks the highest-priority match first.": "فعّل اللغات أدناه ثم رتّبها — يختار المشغل أعلى تطابق حسب الأولوية أولًا.",
  "Language chips: English · Spanish · French · German · Japanese · Korean · Chinese · Arabic · Hindi · Portuguese · Russian · Italian": "شرائح اللغات: الإنجليزية · الإسبانية · الفرنسية · الألمانية · اليابانية · الكورية · الصينية · العربية · الهندية · البرتغالية · الروسية · الإيطالية",
  "Priority order": "ترتيب الأولوية",
  "Subtitle language priority": "أولوية لغة الترجمة",
  "Drag to reorder": "اسحب لإعادة الترتيب",
  "TOP PICK": "الاختيار الأفضل",
  "Subtitles off by default / Don't auto-enable subtitle tracks": "الترجمة متوقفة افتراضيًا / لا تفعّل مسارات الترجمة تلقائيًا",
  "Export": "تصدير",
  "Restore backup / Import a .harbx backup file": "استعادة نسخة احتياطية / استيراد ملف نسخة احتياطية .harbx",
  "Restore": "استعادة",
  "Import backup file": "استيراد ملف النسخة الاحتياطية",
  "Clear local data / Remove all Horse data from this browser": "مسح البيانات المحلية / إزالة جميع بيانات Horse من هذا المتصفح",
  "Clear": "مسح",
  "Local data cleared · (toast description) Reloading…": "تم مسح البيانات المحلية · (toast description) جارٍ إعادة التحميل…",
  "Not a Horse backup file": "ملف النسخة الاحتياطية ليس لبرنامج Horse",
  "Cloud sync": "المزامنة السحابية",
  "Status badge: Off / Up to date / Syncing… / Sync error / Idle": "شارة الحالة: متوقفة / محدثة / جارٍ المزامنة… / خطأ في المزامنة / خاملة",
  "(enabled) Addons, settings, themes, watchlist, continue-watching and history are stored on this server (SQLite). Sign in to Stremio to restore them in any browser; without an account, sync keys to this device.": "(enabled) يتم تخزين الإضافات والإعدادات والسمات وقائمة المشاهدة والمتابعة والسجل على هذا الخادم (SQLite). سجّل الدخول إلى Stremio لاستعادتها في أي متصفح؛ بدون حساب، تتم مزامنة المفاتيح مع هذا الجهاز.",
  "(disabled) Sync is disabled. Your data stays in this browser only — export a backup if you want a second copy.": "(disabled) المزامنة معطلة. تبقى بياناتك في هذا المتصفح فقط — صدّر نسخة احتياطية إذا أردت نسخة ثانية.",
  "Toggle cloud sync": "تبديل المزامنة السحابية",
  "Cloud sync enabled · (toast description) A first sync will start now.": "تم تفعيل المزامنة السحابية · (toast description) ستبدأ أول مزامنة الآن.",
  "Cloud sync disabled · (toast description) Local data stays untouched.": "تم تعطيل المزامنة السحابية · (toast description) ستبقى البيانات المحلية دون تغيير.",
  "Sync now": "مزامنة الآن",
  "Synced · (toast description) Your library is up to date on the server.": "تمت المزامنة · (toast description) مكتبتك محدثة على الخادم.",
  "Horse logo": "شعار Horse",
  "Install app": "تثبيت التطبيق",
  "Installing Horse… · (toast description) Find it in your apps list.": "جارٍ تثبيت Horse… · (toast description) ستجده في قائمة تطبيقاتك.",
  "Installed as app": "مثبت كتطبيق",
  "An independent web client for the Stremio addon protocol — a web port of the Harbor desktop app by the Harbor project (github.com/harborstremio/harbor), MIT licensed.": "عميل ويب مستقل لبروتوكول إضافات Stremio — منفذ ويب لتطبيق Harbor المكتبي من مشروع Harbor (github.com/harborstremio/harbor)، مرخص بموجب MIT.",
  "Horse is an independent, open-source media center for the Stremio addon protocol. It is not affiliated with Stremio. It hosts, indexes, and ships no media and bundles no content addons — users install their own addons.": "Horse مركز وسائط مستقل ومفتوح المصدر لبروتوكول إضافات Stremio. ولا يرتبط بـStremio. لا يستضيف الوسائط ولا يفهرسها ولا يوزعها، ولا يضم إضافات محتوى — يثبت المستخدمون إضافاتهم بأنفسهم.",
  "Licensed MIT. Attribution: Harbor desktop (github.com/harborstremio/harbor).": "مرخص بموجب MIT. الإسناد: Harbor desktop (github.com/harborstremio/harbor).",
  "TMDB attribution line — component defined in chrome/tmdb-card.tsx": "سطر إسناد TMDB — المكون معرّف في chrome/tmdb-card.tsx",
  "Keyboard shortcuts": "اختصارات لوحة المفاتيح",
  "/ — Focus search": "/ — التركيز على البحث",
  "Space — Play / pause": "Space — تشغيل / إيقاف مؤقت",
  "F — Fullscreen": "F — ملء الشاشة",
  "← / → — Seek ±10s": "← / → — التقديم ±10ث",
  "↑ / ↓ — Volume": "↑ / ↓ — مستوى الصوت",
  "M — Mute": "M — كتم الصوت",
  "S / C — Cycle subtitles": "S / C — التنقل بين الترجمات",
  "N / B — Next / prev episode": "N / B — الحلقة التالية / السابقة",
  "W — Stream switcher": "W — تبديل التدفق",
  "E — Episodes panel": "E — لوحة الحلقات",
  "Esc — Close player": "Esc — إغلاق المشغل",
  "0–9 — Seek to %": "0–9 — الانتقال إلى %",
  "Backspace — Back": "Backspace — رجوع",
  "Connect optional third-party services. Activation-code linking keeps tokens encrypted on this app's server; the browser never sees them.": "اربط خدمات اختيارية من جهات خارجية. يحافظ الربط عبر رمز التفعيل على تشفير الرموز المميزة على خادم هذا التطبيق؛ ولا يراها المتصفح مطلقًا.",
  "Disconnect": "قطع الاتصال",
  "Device code": "رمز الجهاز",
  "Waiting for authorization…": "بانتظار التفويض…",
  "Import watchlist": "استيراد قائمة المشاهدة",
  "Import history": "استيراد السجل",
  "Push watchlist": "دفع قائمة المشاهدة",
  "Scrobble to Trakt while playing": "تسجيل المشاهدة في Trakt أثناء التشغيل",
  "Keep watchlist in sync (push additions to Trakt)": "إبقاء قائمة المشاهدة متزامنة (دفع الإضافات إلى Trakt)",
  "Keep watchlist in sync with Trakt": "إبقاء قائمة المشاهدة متزامنة مع Trakt",
  "One-way: additions flow to Trakt a few seconds after you add them. Imports from Trakt are never pushed back, and nothing is ever removed from your Trakt list.": "اتجاه واحد: تنتقل الإضافات إلى Trakt بعد بضع ثوانٍ من إضافتها. لا يتم دفع عمليات الاستيراد من Trakt مرة أخرى، ولا تتم إزالة أي شيء من قائمة Trakt الخاصة بك.",
  "Trakt connected · (toast description) You can now import your watchlist.": "تم ربط Trakt · (toast description) يمكنك الآن استيراد قائمة المشاهدة.",
  "Nothing to push · (toast description) Your watchlist has no imdb-backed titles — install Cinemeta metadata to get imdb ids.": "لا يوجد شيء لدفعه · (toast description) لا تحتوي قائمة المشاهدة على عناوين مرتبطة بـimdb — ثبّت بيانات Cinemeta الوصفية للحصول على معرّفات imdb.",
  "Trakt disconnected": "تم قطع اتصال Trakt",
  "Watchlist sync on · (toast description) Titles you add to your watchlist from now on are pushed to Trakt automatically.": "مزامنة قائمة المشاهدة مفعلة · (toast description) سيتم دفع العناوين التي تضيفها إلى قائمة المشاهدة من الآن فصاعدًا إلى Trakt تلقائيًا.",
  "Trakt connection cancelled": "تم إلغاء اتصال Trakt",
  "PIN code": "رمز PIN",
  "Simkl connected · (toast description) You can now import your watchlist.": "تم ربط Simkl · (toast description) يمكنك الآن استيراد قائمة المشاهدة.",
  "Import failed": "فشل الاستيراد",
  "History import failed": "فشل استيراد السجل",
  "Simkl disconnected": "تم قطع اتصال Simkl",
  "Simkl connection cancelled": "تم إلغاء اتصال Simkl",
  "Premium / Non-premium": "مميز / غير مميز",
  "(aria, tablist) Debrid service": "(aria, tablist) خدمة Debrid",
  "Expires {toLocaleDateString()}": "تنتهي الصلاحية {toLocaleDateString()}",
  "Your Real-Debrid API key / Your AllDebrid API key": "مفتاح API الخاص بـ Real-Debrid / مفتاح API الخاص بـ AllDebrid",
  "Find it on your real-debrid.com/account / alldebrid.com/api page, then validate it here.": "اعثر عليه في صفحة real-debrid.com/account / alldebrid.com/api، ثم تحقّق منه هنا.",
  "Validate": "تحقق",
  "Paste your API key first": "ألصق مفتاح API أولًا",
  "Your key is stored in this browser only and relayed server-side per request. Torrent streams cached by the service unlock instantly; uncached torrents are skipped (honest error).": "يتم تخزين مفتاحك في هذا المتصفح فقط وتمريره من جهة الخادم لكل طلب. تُفتح تدفقات التورنت المخزنة مؤقتًا بواسطة الخدمة فورًا؛ أما التورنتات غير المخزنة مؤقتًا فتُتخطى (خطأ صريح).",
  "Streams unlocked with Debrid — resolved links live only for the current session; nothing is counted or stored.": "تدفقات مفتوحة باستخدام Debrid — تبقى الروابط المحلولة حية خلال الجلسة الحالية فقط؛ ولا يتم احتساب أي شيء أو تخزينه.",
  "P2P Torrent Engine": "محرك تورنت P2P",
  "Play torrents without any account — server-side BitTorrent": "تشغيل التورنتات دون أي حساب — BitTorrent من جهة الخادم",
  "Play torrents via P2P": "تشغيل التورنتات عبر P2P",
  "Join swarms directly when a stream addon only offers torrents. Debrid stays the faster path for cached releases.": "انضم إلى الأسراب مباشرةً عندما توفر إضافة التدفقات تورنتات فقط. يظل Debrid المسار الأسرع للإصدارات المخزنة مؤقتًا.",
  "Toggle P2P torrent playback": "تبديل تشغيل تورنت P2P",
  "Refresh": "تحديث",
  "Torrent engine is not reachable — P2P playback will fail until the torrent-service is running. Debrid playback is unaffected.": "محرك التورنت غير قابل للوصول — سيفشل تشغيل P2P حتى تعمل خدمة التورنت. تشغيل Debrid لا يتأثر.",
  "Torrents download to a server-side cache and stream over HTTP (native containers) or through an ffmpeg remux (mkv). Idle swarms are evicted after 45 minutes; swarms that never find peers are dropped after 90 seconds.": "تُنزّل التورنتات إلى ذاكرة تخزين مؤقت على الخادم وتُبث عبر HTTP (حاويات أصلية) أو من خلال إعادة تغليف ffmpeg (mkv). تتم إزالة الأسراب الخاملة بعد 45 دقيقة؛ وتسقط الأسراب التي لا تجد أقرانًا بعد 90 ثانية.",
  "Stop all": "إيقاف الكل",
  "Wipe cache": "مسح ذاكرة التخزين المؤقت",
  "Torrent cache wiped · (toast description) All downloaded P2P data has been deleted.": "تم مسح ذاكرة تورنت التخزين المؤقت · (toast description) تم حذف جميع بيانات P2P التي تم تنزيلها.",
  "Torrents stopped · (toast description) Active swarms were closed; cache kept for resume.": "تم إيقاف التورنتات · (toast description) تم إغلاق الأسراب النشطة؛ وتم الاحتفاظ بذاكرة التخزين المؤقت للاستئناف.",
  "Back": "رجوع",
  "(aria, brand mark) Horse logo": "(aria, brand mark) شعار Horse",
  "Horse — an open-source media center. Not affiliated with Stremio. Addons are user-installed; Horse hosts no content.": "Horse — مركز وسائط مفتوح المصدر. غير تابع لـStremio. الإضافات يثبتها المستخدمون؛ ولا يستضيف Horse أي محتوى.",
  "Inspired by the Harbor desktop app: github.com/harborstremio/harbor (MIT). This is a web port.": "مستوحى من تطبيق Harbor المكتبي: github.com/harborstremio/harbor (MIT). هذا منفذ ويب.",
  "This product uses the TMDB API but is not endorsed or certified by TMDB.": "يستخدم هذا المنتج واجهة TMDB API، لكنه غير معتمد أو مصدّق من TMDB.",
  "(aria, dialog) Shared theme": "(aria, dialog) السمة المشتركة",
  "Previewing now — keep it or restore your previous look.": "تجري المعاينة الآن — احتفظ بها أو استعد مظهرك السابق.",
  "Keep theme": "الاحتفاظ بالسمة",
  "Discard": "تجاهل",
  "(aria, dialog) Shared list": "(aria, dialog) القائمة المشتركة",
  "Add to my lists": "إضافة إلى قوائمي",
  "(toast, description) “{list name}” was added to your lists. (dynamic)": "(toast, description) تمت إضافة «{list name}» إلى قوائمك. (dynamic)",
  "Public demo stream": "تدفق تجريبي عام",
  "Home": "الرئيسية",
  "Discover": "استكشف",
  "Shows": "المسلسلات",
  "Kids": "الأطفال",
  "Live TV": "البث التلفزيوني المباشر",
  "Calendar": "التقويم",
  "Library": "المكتبة",
  "Addons": "الإضافات",
  "Wrapped": "حصاد المشاهدة",
  "(aria, nav) Primary navigation": "(aria, nav) التنقل الرئيسي",
  "(aria, tablist) Primary": "(aria, tablist) الرئيسية",
  "(aria, phone trigger button) Search": "(aria, phone trigger button) بحث",
  "Search…": "بحث…",
  "(aria, input) Search movies, series, people and addons": "(aria, input) البحث عن الأفلام والمسلسلات والأشخاص والإضافات",
  "AI search: describe what you feel like watching": "بحث بالذكاء الاصطناعي: صف ما ترغب في مشاهدته",
  "(aria, listbox) Search suggestions": "(aria, listbox) اقتراحات البحث",
  "Search failed — check your connection and try again.": "فشل البحث — تحقق من اتصالك وحاول مرة أخرى.",
  "Recent": "الأخيرة",
  "Trending now": "الرائج الآن",
  "Series|Movie": "مسلسل|فيلم",
  "Series": "المسلسلات",
  "Go to / انتقال سريع": "انتقال إلى / انتقال سريع",
  "People": "الأشخاص",
  "From your addons": "من إضافاتك",
  "Person": "شخص",
  "No quick matches — press Enter for full results.": "لا توجد مطابقات سريعة — اضغط Enter للحصول على النتائج الكاملة.",
  "(aria, dialog) Search": "(aria, dialog) بحث",
  "Close search": "إغلاق البحث",
  "(aria, input) Search query": "(aria, input) استعلام البحث",
  "Search movies, series, addons…": "البحث عن الأفلام والمسلسلات والإضافات…",
  "(placeholder, AI mode) Describe what you feel like watching… (Enter)": "(placeholder, AI mode) صف ما ترغب في مشاهدته… (Enter)",
  "AI mode: describe what you want to watch": "وضع الذكاء الاصطناعي: صف ما تريد مشاهدته",
  "Clear query": "مسح الاستعلام",
  "Search failed. Check your connection and try again.": "فشل البحث. تحقق من اتصالك وحاول مرة أخرى.",
  "Something went wrong. Try again.": "حدث خطأ ما. حاول مرة أخرى.",
  "AI Picks": "اختيارات الذكاء الاصطناعي",
  "Go to": "انتقال إلى",
  "Install more addons to expand your catalog coverage.": "ثبّت المزيد من الإضافات لتوسيع نطاق تغطية الكتالوج.",
  "Type to search Cinemeta and your installed addons.": "اكتب للبحث في Cinemeta وإضافاتك المثبتة.",
  "Tip: toggle AI mode to describe what you feel like watching.": "نصيحة: فعّل وضع الذكاء الاصطناعي لوصف ما ترغب في مشاهدته.",
  "(aria, dialog) Command palette": "(aria, dialog) لوحة الأوامر",
  "Type a command or search…": "اكتب أمرًا أو ابحث…",
  "(aria, input) Command palette search": "(aria, input) البحث في لوحة الأوامر",
  "(aria, spinner status) Searching content": "(aria, spinner status) جارٍ البحث في المحتوى",
  "Close command palette": "إغلاق لوحة الأوامر",
  "(aria, listbox) Commands": "(aria, listbox) الأوامر",
  "Try “settings” or a title from your library": "جرّب “settings” أو عنوانًا من مكتبتك",
  "Recent · Navigate · Settings · Actions · Library · Movies · Series · Addon results · Addons · Search": "الأخيرة · التنقل · الإعدادات · الإجراءات · المكتبة · الأفلام · المسلسلات · نتائج الإضافات · الإضافات · البحث",
  "Settings · Basics": "الإعدادات · الأساسيات",
  "Settings · Player": "الإعدادات · المشغل",
  "Settings · Theme": "الإعدادات · المظهر",
  "Settings · Language": "الإعدادات · اللغة",
  "Settings · Integrations": "الإعدادات · التكاملات",
  "Settings · Data": "الإعدادات · البيانات",
  "Settings · About": "الإعدادات · حول",
  "Toggle Kids Mode": "تبديل وضع الأطفال",
  "Shuffle theme": "تبديل السمة",
  "Search content": "البحث في المحتوى",
  "Addon: {addon name} (dynamic)": "إضافة: {addon name} (dynamic)",
  "↑ ↓ navigate": "↑ ↓ للتنقل",
  "↵ select": "↵ للتحديد",
  "esc close": "esc للإغلاق",
  "≥2 chars searches Cinemeta + addons": "≥2 أحرف للبحث في Cinemeta + الإضافات",
  "ctrl K toggle": "ctrl K للتبديل",
  "Quick Access / الوصول السريع": "الوصول السريع / Quick Access",
  "Everything that used to live in the sidebar / كل الصفحات التي كانت في القائمة الجانبية": "كل الصفحات التي كانت موجودة سابقًا في الشريط الجانبي / Everything that used to live in the sidebar",
  "Edit / تعديل": "تعديل / Edit",
  "Done / تم": "تم / Done",
  "(aria, edit: move up) Move earlier / تحريك لأعلى": "(aria, edit: move up) تحريك لأعلى / Move earlier",
  "(aria, edit: move down) Move later / تحريك لأسفل": "(aria, edit: move down) تحريك لأسفل / Move later",
  "(aria, edit: hide) Hide / إخفاء": "(aria, edit: hide) إخفاء / Hide",
  "Show / إظهار": "إظهار / Show",
  "Use the arrows to reorder and the eye to hide — changes save automatically. / استخدم الأسهم لإعادة الترتيب وعلامة العين للإخفاء — يتم الحفظ تلقائياً.": "استخدم الأسهم لإعادة الترتيب والعين للإخفاء — يتم حفظ التغييرات تلقائيًا. / Use the arrows to reorder and the eye to hide — changes save automatically.",
  "Reset to default / استعادة الافتراضي": "استعادة الافتراضي / Reset to default",
  "(aria, back button) Back / رجوع": "(aria, back button) رجوع / Back",
  "(aria, breadcrumb nav) Breadcrumb": "(aria, breadcrumb nav) مسار التنقل",
  "Sign in to Stremio": "تسجيل الدخول إلى Stremio",
  "Your credentials go only to Stremio's official API through our server-side proxy — they are never stored or logged. Syncing imports your addons, watchlist and continue watching.": "تذهب بيانات اعتمادك فقط إلى واجهة Stremio الرسمية عبر وكيلنا من جهة الخادم — ولا يتم تخزينها أو تسجيلها مطلقًا. تستورد المزامنة إضافاتك وقائمة المشاهدة والمتابعة.",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Sign in & sync": "تسجيل الدخول والمزامنة",
  "Not affiliated with Stremio. You can also use Horse without an account.": "غير تابع لـStremio. يمكنك أيضًا استخدام Horse بدون حساب.",
  "Signed in to Stremio": "تم تسجيل الدخول إلى Stremio",
  "(toast, description) Syncing your addons and library…": "(toast, description) جارٍ مزامنة إضافاتك ومكتبتك…",
  "Sync complete": "اكتملت المزامنة",
  "Sync failed": "فشلت المزامنة",
  "Signed out": "تم تسجيل الخروج",
  "Sign in": "تسجيل الدخول",
  "Sign in to sync": "تسجيل الدخول للمزامنة",
  "(aria, mobile icon button) Sign in to Stremio": "(aria, mobile icon button) تسجيل الدخول إلى Stremio",
  "Account menu": "قائمة الحساب",
  "Stremio account": "حساب Stremio",
  "(aria, menu) Account actions": "(aria, menu) إجراءات الحساب",
  "Sign out": "تسجيل الخروج",
  "Add to list": "إضافة إلى القائمة",
  "(aria, menu) Lists": "(aria, menu) القوائم",
  "Your lists": "قوائمك",
  "No lists yet — create your first one below.": "لا توجد قوائم بعد — أنشئ أول قائمة لك أدناه.",
  "Created “{list name}” (dynamic)": "تم إنشاء «{list name}» (dynamic)",
  "(toast, description) {item name} added. (dynamic)": "(toast, description) تمت إضافة {item name}. (dynamic)",
  "Added to {list name} (dynamic)": "تمت الإضافة إلى {list name} (dynamic)",
  "Removed from {list name} (dynamic)": "تمت الإزالة من {list name} (dynamic)",
  "List name…": "اسم القائمة…",
  "Create": "إنشاء",
  "Open library lists": "فتح قوائم المكتبة",
  "(aria, section) Optional integrations to complete your setup": "(aria, section) تكاملات اختيارية لإكمال إعدادك",
  "Complete your Horse setup": "إكمال إعداد Horse",
  "TMDB — Better artwork, title logos, cast & recommendations": "TMDB — أعمال فنية أفضل، وشعارات العناوين، وطاقم العمل والتوصيات",
  "Ratings — IMDb, Rotten Tomatoes, Metacritic & Trakt scores on every title": "Ratings — تقييمات IMDb وRotten Tomatoes وMetacritic وTrakt على كل عنوان",
  "Trakt — Sync scrobbles, watchlist & history with link a code": "Trakt — مزامنة scrobbles وقائمة المشاهدة والسجل عبر ربط رمز",
  "Simkl — Track what you watch across devices with a PIN code": "Simkl — تتبع ما تشاهده عبر الأجهزة باستخدام رمز PIN",
  "Active / Not set up": "نشط / لم يتم الإعداد",
  "Set up in Settings → Integrations": "الإعداد في الإعدادات ← التكاملات",
  "Anime ratings (AniList · MyAnimeList · Kitsu) work without any keys.": "تعمل تقييمات الأنمي (AniList · MyAnimeList · Kitsu) بدون أي مفاتيح.",
  "(aria, dismiss) Dismiss setup suggestions": "(aria, dismiss) تجاهل اقتراحات الإعداد",
  "Visit {verification URL host} and enter this code: (dynamic — URL rendered as link text)": "انتقل إلى {verification URL host} وأدخل هذا الرمز: (dynamic — URL rendered as link text)",
  "(tooltip, code button) Click to copy": "(tooltip, code button) انقر للنسخ",
  "Expires in {mm:ss} (dynamic countdown)": "تنتهي الصلاحية خلال {mm:ss} (dynamic countdown)",
  "(aria, timer) Code expires in": "(aria, timer) تنتهي صلاحية الرمز خلال",
  "(tooltip, QR) Scan to open the verification page": "(tooltip, QR) امسح لفتح صفحة التحقق",
  "(alt, QR image) QR code linking to {verification URL} (dynamic)": "(alt, QR image) رمز QR المرتبط بـ{verification URL} (dynamic)",
  "Approve on the provider's site and this connects automatically within seconds.": "وافق على موقع الخدمة وسيتصل تلقائيًا خلال ثوانٍ.",
  "New code": "رمز جديد",
  "{Service name} connected (dynamic — also a toast title)": "تم ربط {Service name} (dynamic — also a toast title)",
  "(toast, description) Tokens are stored securely on your server.": "(toast, description) يتم تخزين الرموز المميزة بأمان على خادمك.",
  "Synced {Service name} (dynamic)": "تمت مزامنة {Service name} (dynamic)",
  "The code expired — generate a new one.": "انتهت صلاحية الرمز — أنشئ رمزًا جديدًا.",
  "Access was denied on the provider's site. You can start again.": "تم رفض الوصول من موقع الخدمة. يمكنك البدء من جديد.",
  "Something went wrong — try again.": "حدث خطأ ما — حاول مرة أخرى.",
  "Generate new code": "إنشاء رمز جديد",
  "Copy failed": "فشل النسخ",
  "(toast, description) Select the code and copy it manually.": "(toast, description) حدّد الرمز وانسخه يدويًا.",
  "(toast, description) Check your connection and try again.": "(toast, description) تحقق من اتصالك وحاول مرة أخرى.",
  "Unlink": "إلغاء الربط",
  "(aria, group) Ratings": "(aria, group) التقييمات",
  "No ratings available": "لا تتوفر تقييمات",
  "Provider labels rendered on chips (registry): IMDb · Rotten Tomatoes · Metacritic · TMDB · Trakt · MDBList · AniList · MyAnimeList · Kitsu": "تسميات المزودين المعروضة على الشرائح (السجل): IMDb · Rotten Tomatoes · Metacritic · TMDB · Trakt · MDBList · AniList · MyAnimeList · Kitsu",
  "Ratings": "التقييمات",
  "Scores shown on detail pages. Providers without a configured key are hidden automatically; anime titles also pull AniList / MAL / Kitsu.": "التقييمات المعروضة في صفحات التفاصيل. يتم إخفاء المزودين الذين لا يحتويون على مفتاح مهيأ تلقائيًا؛ كما تجلب عناوين الأنمي AniList / MAL / Kitsu.",
  "Enabled": "مفعّل",
  "(aria, list) Ratings providers (order = display order)": "(aria, list) مزودو التقييمات (الترتيب = ترتيب العرض)",
  "default position": "الموضع الافتراضي",
  "Move {provider label} up (dynamic)": "تحريك {provider label} لأعلى (dynamic)",
  "Move {provider label} down (dynamic)": "تحريك {provider label} لأسفل (dynamic)",
  "Ordered / Default": "مرتب / افتراضي",
  "“Ordered” providers appear first in the given sequence; everything else follows in default order. Hidden automatically when a provider has no data or no key.": "يظهر المزودون «المرتّبون» أولًا بالترتيب المحدد؛ ويتبعهم كل ما عدا ذلك بالترتيب الافتراضي. ويتم إخفاؤهم تلقائيًا عند عدم توفر بيانات أو مفتاح للمزود.",
  "(aria, dialog) Keyboard shortcuts": "(aria, dialog) اختصارات لوحة المفاتيح",
  "Work anywhere in Horse.": "اعمل في أي مكان داخل Horse.",
  "Close shortcuts help": "إغلاق مساعدة الاختصارات",
  "Search (instant results) — Ctrl K": "البحث (نتائج فورية) — Ctrl K",
  "Search — /": "البحث — /",
  "Command palette (navigate & settings) — Ctrl Shift P": "لوحة الأوامر (التنقل والإعدادات) — Ctrl Shift P",
  "This shortcuts help — ?": "مساعدة الاختصارات هذه — ?",
  "Close overlays / dialogs — Esc": "إغلاق النوافذ / الحوارات — Esc",
  "Go back — Backspace, Alt+←": "رجوع — Backspace، Alt+←",
  "Play / pause — Space": "تشغيل / إيقاف مؤقت — Space",
  "Seek back / forward — ← →": "تقديم للخلف / للأمام — ← →",
  "Volume up / down — ↑ ↓": "رفع / خفض مستوى الصوت — ↑ ↓",
  "Mute — M": "كتم الصوت — M",
  "Fullscreen (double-click also works) — F": "ملء الشاشة (النقر المزدوج يعمل أيضًا) — F",
  "Picture-in-picture — U": "صورة داخل صورة — U",
  "Cycle subtitles — S C": "التنقل بين الترجمات — S C",
  "Switch stream — W": "تبديل التدفق — W",
  "Next episode (series) — N": "الحلقة التالية (المسلسل) — N",
  "Jump to 0–90% of the video — 0 … 9": "الانتقال إلى 0–90% من الفيديو — 0 … 9",
  "Jump to start / end — Home End": "الانتقال إلى البداية / النهاية — Home End",
  "Tip: press Ctrl K for instant search results, or Ctrl Shift P for the command palette — together they search everywhere.": "نصيحة: اضغط Ctrl K للحصول على نتائج بحث فورية، أو Ctrl Shift P لفتح لوحة الأوامر — معًا يبحثان في كل مكان.",
  "Design your own theme with live preview. Save it to reuse, or export and share it. Your accent color seeds the Material 3 palette.": "صمّم مظهرك الخاص مع معاينة مباشرة. احفظه لإعادة استخدامه، أو صدّره وشاركه. لونك المميز هو الأساس للوحة Material 3.",
  "(aria, strip) Saved themes": "(aria, strip) السمات المحفوظة",
  "Copy share link": "نسخ رابط المشاركة",
  "Palette": "لوحة الألوان",
  "Your accent color seeds the Material 3 palette — tones, containers and surfaces are derived from it.": "لونك المميز هو الأساس للوحة Material 3 — وتُشتق منه الدرجات والحاويات والأسطح.",
  "Color field labels + hints (10 rows):": "تسميات وتلميحات حقول الألوان (10 صفوف):",
  "Typography": "الخطوط",
  "Font pair chips (from FONT_PAIRS registry): Sentient / Switzer · Fraunces / Inter · General Sans · Cabinet / Switzer · IBM Plex · Plus Jakarta · System": "شرائح أزواج الخطوط (من سجل FONT_PAIRS): Sentient / Switzer · Fraunces / Inter · General Sans · Cabinet / Switzer · IBM Plex · Plus Jakarta · System",
  "Structure": "البنية",
  "Layout *(select label)* — options: sidebar, stremio, topdock, rail, dracula, nord, forest, royal": "التخطيط *(select label)* — الخيارات: sidebar, stremio, topdock, rail, dracula, nord, forest, royal",
  "Cards *(select label)* — options: flat, glass, stremio, crunch, noir, glossy": "البطاقات *(select label)* — الخيارات: flat, glass, stremio, crunch, noir, glossy",
  "Buttons *(select label)* — options: flat, crunch, noir, glossy": "الأزرار *(select label)* — الخيارات: flat, crunch, noir, glossy",
  "(placeholder, name input) Theme name": "(placeholder, name input) اسم السمة",
  "Save theme": "حفظ السمة",
  "From link": "من رابط",
  "Import": "استيراد",
  "Reset preview": "إعادة ضبط المعاينة",
  "(aria, hidden file input) Import theme file": "(aria, hidden file input) استيراد ملف السمة",
  "(aria, dialog) Import theme from link": "(aria, dialog) استيراد السمة من رابط",
  "Theme link": "رابط السمة",
  "Paste a shared theme link (or the raw hbtheme1 code). Nothing is sent to any server.": "ألصق رابط سمة مشتركة (أو رمز hbtheme1 الخام). لا يتم إرسال أي شيء إلى أي خادم.",
  "Apply link": "تطبيق الرابط",
  "Invalid colors": "ألوان غير صالحة",
  "(toast, description) Fix the highlighted color values before saving.": "(toast, description) أصلح قيم الألوان المميزة قبل الحفظ.",
  "Theme saved": "تم حفظ السمة",
  "(toast, description) Anyone opening it can preview the theme.": "(toast, description) يمكن لأي شخص يفتحه معاينة السمة.",
  "Invalid theme link": "رابط سمة غير صالح",
  "(toast, description) Paste a harbor theme link you received.": "(toast, description) ألصق رابط سمة Harbor الذي استلمته.",
  "Theme link applied": "تم تطبيق رابط السمة",
  "(toast, description) Previewing — save it to keep it.": "(toast, description) تجري المعاينة — احفظها للاحتفاظ بها.",
  "Theme imported": "تم استيراد السمة",
  "(toast, description) Previewing imported theme — save it to keep it.": "(toast, description) تجري معاينة السمة المستوردة — احفظها للاحتفاظ بها.",
  "Not a Horse theme file": "ملف السمة ليس لبرنامج Horse",
  "Theme file contains invalid colors": "يحتوي ملف السمة على ألوان غير صالحة",
  "My theme": "سمتي",
  "Shared theme": "السمة المشتركة",
  "TMDB metadata": "بيانات TMDB الوصفية",
  "Posters, backdrops, logos, cast, certifications and better search — layered on top of your addons.": "ملصقات وخلفيات وشعارات وطاقم عمل وشهادات وتصحيح بحث أفضل — مضافة فوق إضافاتك.",
  "(aria, switch) Enable TMDB metadata": "(aria, switch) تفعيل بيانات TMDB الوصفية",
  "Checking server key…": "جارٍ التحقق من مفتاح الخادم…",
  "Server TMDB key active (set via environment).": "مفتاح TMDB للخادم نشط (تم تعيينه عبر البيئة).",
  "No server key — add your own below to enable TMDB.": "لا يوجد مفتاح خادم — أضف مفتاحك أدناه لتفعيل TMDB.",
  "Metadata language": "لغة البيانات الوصفية",
  "Titles, overviews and images returned by TMDB.": "العناوين والملخصات والصور التي يعيدها TMDB.",
  "(aria, select) TMDB metadata language": "(aria, select) لغة بيانات TMDB الوصفية",
  "Option labels: English · العربية (Arabic) · Español · Français · Deutsch · Português (BR) · Italiano · Türkçe · Русский · 日本語 · 한국어 · 简体中文": "تسميات الخيارات: الإنجليزية · العربية · الإسبانية · الفرنسية · الألمانية · البرتغالية (BR) · الإيطالية · التركية · الروسية · اليابانية · الكورية · الصينية المبسطة",
  "Image quality": "جودة الصورة",
  "Higher looks sharper but downloads more bytes.": "الجودة الأعلى تبدو أكثر حدة لكنها تنزّل عددًا أكبر من وحدات البايت.",
  "(aria, group) Image quality": "(aria, group) جودة الصورة",
  "low / medium / high": "منخفضة / متوسطة / عالية",
  "Your own TMDB API key (optional)": "مفتاح TMDB API الخاص بك (اختياري)",
  "v3 key (32 hex chars) or v4 Read Access Token": "مفتاح v3 (32 حرفًا سداسيًا عشريًا) أو رمز وصول القراءة v4",
  "Valid v4 Read Access Token / Valid v3 API key": "رمز وصول قراءة v4 صالح / مفتاح API v3 صالح",
  "— saved.": "— تم الحفظ.",
  "TMDB rejected this key.": "رفض TMDB هذا المفتاح.",
  "Could not reach TMDB to validate — check your connection.": "تعذر الوصول إلى TMDB للتحقق — تحقق من اتصالك.",
  "Get a free key in ~1 minute:": "احصل على مفتاح مجاني في نحو دقيقة واحدة:",
  "Create a free account at themoviedb.org.": "أنشئ حسابًا مجانيًا على themoviedb.org.",
  "Open Settings → API and copy the API Key (v3) — or the longer API Read Access Token (v4).": "افتح الإعدادات ← API وانسخ مفتاح API (v3) — أو رمز وصول API للقراءة الأطول (v4).",
  "Paste it above. It is validated live, stays in this browser only, and TMDB features switch on immediately.": "ألصقه أعلاه. يتم التحقق منه مباشرةً، ويبقى في هذا المتصفح فقط، وتعمل ميزات TMDB فورًا.",
  "(everything else is data plumbing; no other user-facing text)": "(كل ما عدا ذلك معالجة بيانات؛ لا توجد نصوص أخرى ظاهرة للمستخدم)",
  "View all": "عرض الكل",
  "RailSkeleton: aria-hidden, no text": "RailSkeleton: aria-hidden، لا يوجد نص",
  "— (no static user-facing text)": "— (لا يوجد نص ثابت ظاهر للمستخدم)",
  "Finding the best stream…": "جارٍ العثور على أفضل تدفق…",
  "Joining the torrent swarm… (dynamic)": "جارٍ الانضمام إلى سرب التورنت… (dynamic)",
  "Checking video codecs… (dynamic)": "جارٍ التحقق من برامج ترميز الفيديو… (dynamic)",
  "No streams found from your addons.": "لم يتم العثور على تدفقات من إضافاتك.",
  "No browser-playable stream found. Open the stream picker to choose manually — torrent streams play via P2P or unlock with debrid.": "لم يتم العثور على تدفق قابل للتشغيل في المتصفح. افتح منتقي التدفقات للاختيار يدويًا — تعمل تدفقات التورنت عبر P2P أو تُفتح باستخدام debrid.",
  "No peers responded for the best torrent. Open the stream picker to pick another source, or connect debrid for instant cached streams.": "لم يستجب أي نظير لأفضل تورنت. افتح منتقي التدفقات لاختيار مصدر آخر، أو اربط debrid للحصول على تدفقات مخزنة مؤقتًا بشكل فوري.",
  "Torrent engine could not serve this file. Try another stream in the picker.": "تعذر على محرك التورنت تقديم هذا الملف. جرّب تدفقًا آخر في المنتقي.",
  "P2P swarm": "سرب P2P",
  "Failed to resolve streams": "فشل حل التدفقات",
  "Close player (Esc)": "إغلاق المشغل (Esc)",
  "Leave playback?": "مغادرة التشغيل؟",
  "Switch stream (W)": "تبديل التدفق (W)",
  "Retrying through the secure proxy… / إعادة المحاولة عبر الوسيط الآمن…": "جارٍ إعادة المحاولة عبر الوكيل الآمن… / إعادة المحاولة عبر الوسيط الآمن…",
  "Converting this stream for your browser… / جارٍ تحويل هذا البث لمتصفحك…": "جارٍ تحويل هذا التدفق لمتصفحك… / جارٍ تحويل هذا البث لمتصفحك…",
  "Trying another source… / جرب مصدراً آخر…": "جارٍ تجربة مصدر آخر… / جرب مصدراً آخر…",
  "Playback problem / مشكلة في التشغيل": "مشكلة في التشغيل / مشكلة في التشغيل",
  "Convert and play / حوّل وشغّل": "تحويل وتشغيل / حوّل وشغّل",
  "Retry / إعادة المحاولة": "إعادة المحاولة / إعادة المحاولة",
  "Pick another stream / اختر بثاً آخر": "اختيار تدفق آخر / اختر بثاً آخر",
  "Show technical details / إظهار التفاصيل التقنية": "إظهار التفاصيل التقنية / إظهار التفاصيل التقنية",
  "Copy diagnostics / نسخ التشخيص": "نسخ بيانات التشخيص / نسخ التشخيص",
  "Diagnostics copied / تم نسخ التشخيص": "تم نسخ بيانات التشخيص / تم نسخ التشخيص",
  "This format needs conversion / هذه الصيغة تحتاج إلى تحويل": "هذه الصيغة تحتاج إلى تحويل / هذه الصيغة تحتاج إلى تحويل",
  "The link expired or is unavailable / انتهت صلاحية الرابط أو أنه غير متاح": "انتهت صلاحية الرابط أو أنه غير متاح / انتهت صلاحية الرابط أو أنه غير متاح",
  "Network hiccup — retrying… / انقطاع في الشبكة — إعادة المحاولة…": "انقطاع في الشبكة — إعادة المحاولة… / انقطاع في الشبكة — إعادة المحاولة…",
  "The source blocks playback. / المصدر يمنع التشغيل.": "المصدر يمنع التشغيل. / المصدر يمنع التشغيل.",
  "Torrents can't play natively in browsers. This one needs the built-in P2P engine or a debrid unlock. / لا يمكن للمتصفحات تشغيل التورنت مباشرة. يحتاج هذا البث إلى محرك P2P المدمج أو فتح عبر Debrid.": "لا يمكن للمتصفحات تشغيل التورنت مباشرة. يحتاج هذا البث إلى محرك P2P المدمج أو فتح عبر Debrid. / لا يمكن للمتصفحات تشغيل التورنت مباشرة. يحتاج هذا البث إلى محرك P2P المدمج أو فتح عبر Debrid.",
  "(aria, alertdialog) This format needs conversion / هذه الصيغة تحتاج إلى تحويل": "(aria, alertdialog) هذه الصيغة تحتاج إلى تحويل / هذه الصيغة تحتاج إلى تحويل",
  "This format needs conversion": "هذه الصيغة تحتاج إلى تحويل",
  "The server can convert this stream to a browser-friendly format (H.264/AAC). Conversion takes time and CPU. / يمكن للخادم تحويل هذا البث إلى صيغة متوافقة (H.264/AAC). قد يستهلك التحويل وقتاً ومعالجة.": "يمكن للخادم تحويل هذا التدفق إلى صيغة متوافقة مع المتصفح (H.264/AAC). يستغرق التحويل وقتًا ويستهلك CPU. / يمكن للخادم تحويل هذا البث إلى صيغة متوافقة (H.264/AAC). قد يستهلك التحويل وقتاً ومعالجة.",
  "Downloading via P2P…": "جارٍ التنزيل عبر P2P…",
  "transmuxed — seeking restarts the transcoder at the target position": "تم إجراء transmux — يؤدي التقديم إلى إعادة تشغيل المحوّل عند الموضع المستهدف",
  "Server-side P2P torrent stream": "تدفق تورنت P2P من جهة الخادم",
  "(aria, alert) Up next episode": "(aria, alert) الحلقة التالية",
  "Up next": "التالي",
  "now": "الآن",
  "Next episode": "الحلقة التالية",
  "Pause (Space) / Play (Space)": "إيقاف مؤقت (Space) / تشغيل (Space)",
  "Mute (M) / Unmute (M)": "كتم (M) / إلغاء الكتم (M)",
  "(aria, volume slider) Volume": "(aria, volume slider) مستوى الصوت",
  "(aria, button) Subtitles (S)": "(aria, button) الترجمات (S)",
  "Subtitles": "الترجمات",
  "(aria, group) Filter subtitles by language": "(aria, group) تصفية الترجمات حسب اللغة",
  "Filter subtitles…": "تصفية الترجمات…",
  "(aria, filter input) Filter subtitles by name, language or provider": "(aria, filter input) تصفية الترجمات حسب الاسم أو اللغة أو المزود",
  "(aria, clear filter) Clear subtitle filter": "(aria, clear filter) مسح عامل تصفية الترجمة",
  "Off": "إيقاف",
  "No subtitles found for this title.": "لم يتم العثور على ترجمات لهذا العنوان.",
  "Load local file (.srt / .vtt)": "تحميل ملف محلي (.srt / .vtt)",
  "No readable cues found in that file.": "لم يتم العثور على أسطر قابلة للقراءة في هذا الملف.",
  "This subtitle is already loaded.": "هذه الترجمة محملة بالفعل.",
  "Local file": "ملف محلي",
  "(aria, button) Playback settings": "(aria, button) إعدادات التشغيل",
  "Speed": "السرعة",
  "Quality": "الجودة",
  "Auto": "تلقائي",
  "Adaptive bitrate": "معدل البت التكيفي",
  "Now playing {level label} (dynamic — Auto chip while auto mode plays a level)": "يُشغّل الآن {level label} (dynamic — Auto chip while auto mode plays a level)",
  "Audio": "الصوت",
  "Video fit": "ملاءمة الفيديو",
  "Fit / Fill / Zoom": "احتواء / ملء / تكبير",
  "Picture in picture (U)": "صورة داخل صورة (U)",
  "Fullscreen (F) / Exit fullscreen (F)": "ملء الشاشة (F) / الخروج من ملء الشاشة (F)",
  "(aria, slider label) Seek": "(aria, slider label) تقديم",
  "(aria, valuetext, unknown length) Elapsed {spoken time}, total length unknown (dynamic)": "(aria, valuetext, unknown length) المنقضي {spoken time}، المدة الإجمالية غير معروفة (dynamic)",
  "Seek — click, drag, or use arrow keys": "تقديم — انقر أو اسحب أو استخدم مفاتيح الأسهم",
  "(tooltip, unknown length) Total length unknown for this stream — showing elapsed time; seeking may be limited": "(tooltip, unknown length) المدة الإجمالية غير معروفة لهذا التدفق — يتم عرض الوقت المنقضي؛ وقد يكون التقديم محدودًا",
  "Toggle elapsed / remaining time": "تبديل الوقت المنقضي / المتبقي",
  "(tooltip, unknown length) Total length unknown — showing elapsed time": "(tooltip, unknown length) المدة الإجمالية غير معروفة — يتم عرض الوقت المنقضي",
  "Time: {spoken time} of {spoken duration}. Activate to toggle remaining time display. (dynamic)": "الوقت: {spoken time} من {spoken duration}. فعّل لتبديل عرض الوقت المتبقي. (dynamic)",
  "(aria, unknown length) Time: Elapsed {spoken time}, total length unknown. Activate to toggle remaining time display. (dynamic)": "(aria, unknown length) الوقت: المنقضي {spoken time}، المدة الإجمالية غير معروفة. فعّل لتبديل عرض الوقت المتبقي. (dynamic)",
  "length unknown / المدة غير معروفة": "المدة غير معروفة / المدة غير معروفة",
  "\"sync failed\" — cloud-sync status error fallback (shown in Settings sync status)": "\"فشلت المزامنة\" — البديل لحالة خطأ cloud-sync (يظهر في حالة مزامنة الإعدادات)",
  "\"Login failed\" — account modal login error fallback": "\"فشل تسجيل الدخول\" — البديل لخطأ تسجيل الدخول في نافذة الحساب",
  "\"Network error — try again\" — account modal": "\"خطأ في الشبكة — حاول مرة أخرى\" — نافذة الحساب",
  "\"sync failed\" — syncAll catch fallback": "\"فشلت المزامنة\" — البديل لخطأ syncAll",
  "\"HEVC/DoVi video needs conversion, which is disabled on this server\"": "\"فيديو HEVC/DoVi يحتاج إلى تحويل، وهو معطل على هذا الخادم\"",
  "\"HEVC/DoVi video will be converted to H.264\"": "\"سيتم تحويل فيديو HEVC/DoVi إلى H.264\"",
  "\"no playable source in this stream object\"": "\"لا يوجد مصدر قابل للتشغيل في كائن التدفق هذا\"",
  "\"addon marked this stream not-web-ready\"": "\"وضعت الإضافة علامة على هذا التدفق بأنه غير جاهز للويب\"",
  "\"http source on an https page — mixed content is blocked\"": "\"مصدر http على صفحة https — تم حظر المحتوى المختلط\"",
  "\"audio (AC3/DTS/TrueHD) will be converted to AAC\"": "\"سيتم تحويل الصوت (AC3/DTS/TrueHD) إلى AAC\"",
  "\"signing failed\" — fallback when /api/media/sign returns no error field": "\"فشل التوقيع\" — البديل عند عدم إرجاع /api/media/sign لحقل خطأ",
  "(technical) \"MEDIA_ERR_ABORTED\" / \"MEDIA_ERR_NETWORK\" / \"MEDIA_ERR_DECODE\" / \"MEDIA_ERR_SRC_NOT_SUPPORTED\" / \"UNKNOWN\" — classified failure message fallbacks (technical-details panel)": "(technical) \"MEDIA_ERR_ABORTED\" / \"MEDIA_ERR_NETWORK\" / \"MEDIA_ERR_DECODE\" / \"MEDIA_ERR_SRC_NOT_SUPPORTED\" / \"UNKNOWN\" — بدائل رسائل الفشل المصنفة (لوحة التفاصيل التقنية)",
  "(ui) \"--:--\" — unknown-duration clock display": "(ui) \"--:--\" — عرض ساعة المدة غير المعروفة",
  "(ui) \"0 KB/s\" — formatSpeed zero state": "(ui) \"0 KB/s\" — حالة formatSpeed الصفرية",
  "(ui) \"—\" — formatEta zero state": "(ui) \"—\" — حالة formatEta الصفرية",
  "(label) \"Subtitle\" — final fallback label in subLabel() (subtitle menu entry)": "(label) \"ترجمة\" — التسمية الاحتياطية النهائية في subLabel() (عنصر قائمة الترجمة)",
  "\"gzipped subtitle unsupported\" — subtitle load failure": "\"الترجمة المضغوطة بصيغة gzip غير مدعومة\" — فشل تحميل الترجمة",
  "(ui) \"SUB\" — langChip fallback chip when no language can be derived": "(ui) \"SUB\" — شريحة بديلة عندما يتعذر اشتقاق أي لغة",
  "\"Invalid addon manifest\" — thrown when an installed manifest lacks id/name (toast in addon install flow)": "\"بيان الإضافة غير صالح\" — يُرمى عندما يفتقد manifest المثبت إلى id/name (إشعار في تدفق تثبيت الإضافة)",
  "(label) \"Addon\" — fallback source name when an addon manifest has no name": "(label) \"إضافة\" — اسم المصدر الاحتياطي عندما لا يحتوي manifest الخاص بالإضافة على اسم",
  "\"The addon's resource endpoint timed out or returned an error.\" — probe failure body fallback": "\"انتهت مهلة نقطة موارد الإضافة أو أعادت خطأ.\" — البديل لنص فشل الفحص",
  "\"Endpoint replied with zero streams.\"": "\"أعادت نقطة النهاية صفرًا من التدفقات.\"",
  "\"Endpoint replied with zero subtitles.\"": "\"أعادت نقطة النهاية صفرًا من الترجمات.\"",
  "\"Endpoint replied with zero catalog items.\"": "\"أعادت نقطة النهاية صفرًا من عناصر الكتالوج.\"",
  "\"Meta endpoint replied without a meta object.\"": "\"أعادت نقطة نهاية البيانات الوصفية استجابة دون كائن بيانات وصفية.\"",
  "\"Manifest declares no testable resources (stream/subtitles/catalog/meta).\"": "\"لا يعلن manifest عن موارد قابلة للاختبار (stream/subtitles/catalog/meta).\"",
  "\"Request failed\" — probe catch fallback": "\"فشل الطلب\" — بديل catch للفحص",
  "\"Connect a debrid service in Settings → Integrations first\" — resolve without a key": "\"اربط خدمة debrid من الإعدادات ← التكاملات أولًا\" — الحل بدون مفتاح",
  "\"Could not reach the debrid service\" — validate catch fallback": "\"تعذر الوصول إلى خدمة debrid\" — بديل catch للتحقق",
  "\"Unlock request failed\" — resolve catch fallback": "\"فشل طلب فتح القفل\" — بديل catch للحل",
  "\"Could not reach Trakt\" — connect catch fallback": "\"تعذر الوصول إلى Trakt\" — بديل catch للاتصال",
  "\"Device code expired — start again.\"": "\"انتهت صلاحية رمز الجهاز — ابدأ من جديد.\"",
  "\"Connection lost — start again.\"": "\"انقطع الاتصال — ابدأ من جديد.\"",
  "\"Token polling failed\" — pollOnce catch fallback": "\"فشل استقصاء الرمز\" — بديل catch لـpollOnce",
  "\"Import failed\" — watchlist import catch fallback": "\"فشل الاستيراد\" — بديل catch لاستيراد قائمة المشاهدة",
  "\"History import failed\" — history import catch fallback": "\"فشل استيراد السجل\" — بديل catch لاستيراد السجل",
  "\"Push failed\" — pushIds catch fallback": "\"فشل الدفع\" — بديل catch لـpushIds",
  "\"rate limited\" — 429 guard": "\"تم تقييد الطلب\" — حارس 429",
  "\"Trakt blocked this request (Cloudflare). If you self-host, check your server's egress IP.\" — non-JSON 403 upstream": "\"حظر Trakt هذا الطلب (Cloudflare). إذا كنت تستضيف ذاتيًا، فتحقق من عنوان IP للخروج الخاص بخادمك.\" — upstream 403 غير JSON",
  "\"Trakt returned a non-JSON response\" — non-JSON upstream": "\"أعاد Trakt استجابة غير JSON\" — upstream غير JSON",
  "\"upstream timeout\" — 504": "\"انتهت مهلة الخادم الأعلى\" — 504",
  "\"trakt unreachable\" — 502": "\"Trakt غير قابل للوصول\" — 502",
  "(fallback) \"Unknown title\" — watchlist item name fallback (displayed in watchlist)": "(fallback) \"عنوان غير معروف\" — البديل لاسم عنصر قائمة المشاهدة (المعروض في قائمة المشاهدة)",
  "\"Could not reach Simkl\" — connect catch fallback": "\"تعذر الوصول إلى Simkl\" — بديل catch للاتصال",
  "\"PIN code expired — start again.\"": "\"انتهت صلاحية رمز PIN — ابدأ من جديد.\"",
  "\"Simkl rejected this code — start again.\"": "\"رفض Simkl هذا الرمز — ابدأ من جديد.\"",
  "\"Simkl returned a non-JSON response\" — non-JSON upstream": "\"أعاد Simkl استجابة غير JSON\" — upstream غير JSON",
  "\"Simkl rejected the client id\" — 412 envelope fallback": "\"رفض Simkl معرّف العميل\" — بديل envelope 412",
  "\"token expired or revoked\" — 401": "\"انتهت صلاحية الرمز أو تم إلغاؤه\" — 401",
  "\"Simkl unreachable\" — 502": "\"Simkl غير قابل للوصول\" — 502",
  "(fallback) \"Unknown title\" — watchlist/history name fallback": "(fallback) \"عنوان غير معروف\" — بديل اسم قائمة المشاهدة/السجل",
  "(fallback) \"Unknown show\" — history show-name fallback": "(fallback) \"عرض غير معروف\" — بديل اسم العرض في السجل",
  "\"empty anilist response\" — thrown (caught upstream; may surface in view error states)": "\"استجابة anilist فارغة\" — تُرمى (تُلتقط أعلى السلسلة؛ وقد تظهر في حالات خطأ الواجهة)",
  "(fallback) \"Unknown\" — trending item title fallback (displayed)": "(fallback) \"غير معروف\" — البديل لعنوان عنصر رائج (المعروض)",
  "\"TMDB is not configured on this server. Set TMDB_ACCESS_TOKEN (or TMDB_API_KEY) in the environment, or add your own key in Settings → Integrations.\" — 501 unconfigured": "\"لم يتم تهيئة TMDB على هذا الخادم. عيّن TMDB_ACCESS_TOKEN (أو TMDB_API_KEY) في البيئة، أو أضف مفتاحك الخاص في الإعدادات ← التكاملات.\" — 501 غير مهيأ",
  "\"TMDB rate limit reached\" — 429 after retries": "\"تم الوصول إلى حد طلبات TMDB\" — 429 بعد المحاولات",
  "\"TMDB returned non-JSON\"": "\"أعاد TMDB استجابة غير JSON\"",
  "\"Could not reach the server\" — link/start catch fallback": "\"تعذر الوصول إلى الخادم\" — بديل catch لـlink/start",
  "\"Connection hiccup — still trying…\" — poll 5xx/429 transient message": "\"انقطاع في الاتصال — لا تزال المحاولة جارية…\" — رسالة مؤقتة لـpoll 5xx/429",
  "\"List name is required\" — createList throws (caught + shown by the list-creation dialog)": "\"اسم القائمة مطلوب\" — createList يرمي (يُلتقط + يُعرض بواسطة نافذة إنشاء القائمة)",
  "(label) \"Horse\" — preset cool-grey display name": "(label) \"Horse\" — اسم عرض سمة رمادية باردة",
  "(label) \"Sentient / Switzer\" — font pair name": "(label) \"Sentient / Switzer\" — اسم زوج الخطوط",
  "(canvas) \"MY HORSE WRAPPED\" — card header": "(canvas) \"MY HORSE WRAPPED\" — عنوان البطاقة",
  "(canvas) \"TOTAL WATCH TIME\" — hero stat caption": "(canvas) \"TOTAL WATCH TIME\" — تسمية إحصائية رئيسية",
  "(canvas) \"MOVIES\" / \"EPISODES\" / \"ACTIVE DAYS\" — stat block captions": "(canvas) \"MOVIES\" / \"EPISODES\" / \"ACTIVE DAYS\" — تسميات كتل الإحصاءات",
  "(canvas) \"horse — local stats · private by design\" — card footer": "(canvas) \"horse — local stats · private by design\" — تذييل البطاقة",
  "(badge) \"4K\" / \"1080p\" / \"720p\" / \"480p\" / \"SD\" — resolution labels": "(badge) \"4K\" / \"1080p\" / \"720p\" / \"480p\" / \"SD\" — تسميات الدقة",
  "(badge) \"DV\" / \"HDR10+\" / \"HDR10\" — HDR labels": "(badge) \"DV\" / \"HDR10+\" / \"HDR10\" — تسميات HDR",
  "(badge) \"HEVC\" / \"AV1\" / \"VP9\" / \"AVC\" — codec labels": "(badge) \"HEVC\" / \"AV1\" / \"VP9\" / \"AVC\" — تسميات برامج الترميز",
  "(badge) \"REMUX\" / \"BluRay\" / \"WEB-DL\" / \"WEBRip\" / \"DVDRip\" / \"HDTV\" / \"TS\" / \"CAM\" / \"SCR\" — source labels": "(badge) \"REMUX\" / \"BluRay\" / \"WEB-DL\" / \"WEBRip\" / \"DVDRip\" / \"HDTV\" / \"TS\" / \"CAM\" / \"SCR\" — تسميات المصادر",
  "(badge) \"Atmos\" / \"TrueHD\" / \"DTS\" / \"DD+\" / \"AC3\" / \"AAC\" / \"FLAC\" / \"Opus\" — audio labels": "(badge) \"Atmos\" / \"TrueHD\" / \"DTS\" / \"DD+\" / \"AC3\" / \"AAC\" / \"FLAC\" / \"Opus\" — تسميات الصوت",
  "(tier) \"4K HDR\" / \"1080p HDR\" / \"ROUGH\" / \"OTHER\" — tierOf labels (TIER_ORDER)": "(tier) \"4K HDR\" / \"1080p HDR\" / \"ROUGH\" / \"OTHER\" — تسميات tierOf (TIER_ORDER)",
  "\"blocked host\"": "\"تم حظر المضيف\"",
  "\"dns resolve failed\"": "\"فشل حل DNS\"",
  "\"host not allowed\"": "\"المضيف غير مسموح\"",
  "\"invalid url\"": "\"عنوان URL غير صالح\"",
  "\"unsupported protocol\"": "\"البروتوكول غير مدعوم\"",
  "\"credentials in url not allowed\"": "\"بيانات الاعتماد في عنوان URL غير مسموح بها\"",
  "\"too many redirects\"": "\"عمليات إعادة التوجيه كثيرة جدًا\"",
  "\"rate limited\" — /api/proxy 429": "\"تم تقييد الطلب\" — /api/proxy 429",
  "\"missing url\"": "\"عنوان URL مفقود\"",
  "\"upstream fetch failed\" — 502": "\"فشل جلب الخادم الأعلى\" — 502",
  "\"Torrent has no files\" — /prepare 404": "\"لا يحتوي التورنت على ملفات\" — /prepare 404",
  "\"Video conversion is disabled on this server (TRANSCODE_ENABLED).\" — /remux?vtrans 503": "\"تحويل الفيديو معطل على هذا الخادم (TRANSCODE_ENABLED).\" — /remux?vtrans 503",
  "\"Remux busy — try again in a moment\" — /remux 503": "\"إعادة التغليف مشغولة — حاول مرة أخرى بعد لحظة\" — /remux 503",
  // Debrid upstream errors (surface in toasts / inline errors on the phone)
  "Invalid Real-Debrid API key": "مفتاح Real-Debrid غير صالح",
  "Invalid AllDebrid API key": "مفتاح AllDebrid غير صالح",
  "Invalid TorBox API key": "مفتاح TorBox غير صالح",
};
